

spring:
  jpa:
    # see: https://stackoverflow.com/questions/30549489/what-is-this-spring-jpa-open-in-view-true-property-in-spring-boot
    open-in-view: false

server:
  servlet:
    context-path: "/multipoc"
  port: 8014
  max-http-request-header-size: 8KB

management:
  endpoints:
    web:
      base-path: "/actuator"
      exposure:
        include: health, info
    access:
      default: "none"
  endpoint:
    health:
      access: "read-only"
      show-details: "always"
      show-components: "always"
    info:
      access: "read-only"

